// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmxmygsaogvbiemuzarm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhteG15Z3Nhb2d2YmllbXV6YXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDY1MzEsImV4cCI6MjA2OTM4MjUzMX0.V_vK9YiY01U2EwqS7Aw57NeR64T36IQaPr7Z1sdT_Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});